title: Dialektika
lang: cs
description: Web dobrovolného sdružení občanů České republiky Dialektika.
permalink: /:slugified_categories/:title/

include: ["_pages"]

exclude:
  - .cache
  - assets/manifest.json
  - assets/entrypoints.json
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile
  - replit.nix

months:
  - "ledna"
  - "února"
  - "března"
  - "dubna"
  - "května"
  - "června"
  - "července"
  - "srpna"
  - "září"
  - "října"
  - "listopadu"
  - "prosince"
