title: Dialektika
lang: cs
description: Blog serveru Dialektika.cz
permalink: /:slugified_categories/:title/

include: ["_pages"]

exclude:
  - .cache
  - assets/manifest.json
  - assets/entrypoints.json
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile
  - replit.nix

months:
  - "ledna"
  - "února"
  - "března"
  - "dubna"
  - "května"
  - "června"
  - "července"
  - "srpna"
  - "září"
  - "října"
  - "listopadu"
  - "prosince"

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 12
  sort_reverse: true
  sort_field: 'date'
  title: ':title'
  trail:
    before: 2
    after: 2