title: Dialektika
lang: cs
description: Blog serveru Dialektika.cz
permalink: /:slugified_categories/:title/

date_format: "%b %-d, %Y"

exclude:
  - .cache
  - assets/manifest.json
  - assets/entrypoints.json
  - "package*.json"
  - "*.config.js"
  - netlify.toml
  - README.md
  - LICENSE
  - Makefile
  - replit.nix

months:
  - "ledna"
  - "února"
  - "března"
  - "dubna"
  - "května"
  - "června"
  - "července"
  - "srpna"
  - "září"
  - "října"
  - "listopadu"
  - "prosince"